### PR TITLE
fix: add denom units for automatically registered erc 20

### LINKED ISSUE #10: Improvement Suggestion: Add Denom Units for automatically registered ERC-20
Even tho I was suggest not to automatically register ERC-20 pairs before, but during waiting for decision to change and implementation, I have another suggestion to improve current implementation based on observation from the other famous chains.

Ref: [x/erc20/keeper/autoregister_coin.go](https://github.com/dymensionxyz/evmos/blob/5f84f377b4ec81b423e5a2fa6cfb33ec22bd2fbb/x/erc20/keeper/autoregister_coin.go#L11)
and [cosmoshub-4 bank denoms-metadata](https://api-cosmoshub-ia.cosmosia.notional.ventures/cosmos/bank/v1beta1/denoms_metadata)
```json
{
  "metadatas": [
    {
      "description": "The native staking token of the Cosmos Hub.",
      "denom_units": [
        {
          "denom": "uatom", // <= this one
          "exponent": 0,
          "aliases": []
        },
        {
          "denom": "atom",
          "exponent": 6,
          "aliases": []
        }
      ],
      "base": "uatom",
      "display": "atom",
      "name": "Cosmos Hub Atom",
      "symbol": "ATOM"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "1"
  }
}
```

Denom units should have at least one record, with base denom is the `ibc/...` and exponent `0`
I have a tool that observes ~200 chains and the issue, which bank denom-metadata record has no denoms unit, only happens in my RollApp

I have no idea with or without denoms unit, it effects something but this suggestion is just an improvement to sync naming convension with famous chains

### PR DESCRIPTION
**Pull request by mtsitrin**
## Description

----

Closes #XXX

### CODE REVIEW

File: x/erc20/keeper/autoregister_coin.go [hunk 1]
```diff
@@ -8,9 +8,13 @@ import (
 func (k Keeper) AutoRegisterCoin(ctx sdk.Context, traceDenom, baseDenom string) error {
 	metadata := banktypes.Metadata{
 		Description: "auto registered ERC20 for IBC token " + traceDenom,
-		DenomUnits:  []*banktypes.DenomUnit{},
-		Base:        traceDenom,
-		//FIXME: need a define a better way to get the display name and the decimals
```
Comment (VictorTrustyDev) [inline x/erc20/keeper/autoregister_coin.go:13]: mistakenly removed this FIXME?

Comment (mtsitrin) [reply x/erc20/keeper/autoregister_coin.go:13]: it will be handled as separate feature
